################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
C++_DEPS := 
OBJS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
scripting/lua/tolua \
scripting/lua/luajit/LuaJIT-2.0.1/src \
scripting/lua/luajit/LuaJIT-2.0.1/src/host \
scripting/lua/lua \
scripting/lua/cocos2dx_support \
scripting/javascript/bindings \
scripting/javascript/bindings/generated \
obj/local/armeabi/objs/cocos2dcpp_shared/hellocpp \
obj/local/armeabi/objs/cocos2dcpp_shared/__/__/Classes \
obj/local/armeabi/objs/cocos2dcpp_shared/__/__/Classes/JNICalls \
jni/hellocpp \
extensions/spine \
extensions/proj.win32 \
extensions/physics_nodes \
extensions/network \
extensions/LocalStorage \
extensions/GUI/CCScrollView \
extensions/GUI/CCEditBox \
extensions/GUI/CCControlExtension \
extensions/CocoStudio/Reader \
extensions/CocoStudio/Json/lib_json \
extensions/CocoStudio/Json \
extensions/CocoStudio/GUI/UIWidgets \
extensions/CocoStudio/GUI/UIWidgets/ScrollWidget \
extensions/CocoStudio/GUI/System \
extensions/CocoStudio/GUI/Layouts \
extensions/CocoStudio/GUI/BaseClasses \
extensions/CocoStudio/Components \
extensions/CocoStudio/Armature/utils \
extensions/CocoStudio/Armature/physics \
extensions/CocoStudio/Armature/display \
extensions/CocoStudio/Armature/datas \
extensions/CocoStudio/Armature/animation \
extensions/CocoStudio/Armature \
extensions/CocoStudio/Action \
extensions/CCBReader \
extensions/AssetsManager \
cocos2dx/touch_dispatcher \
cocos2dx/tilemap_parallax_nodes \
cocos2dx/textures \
cocos2dx/text_input_node \
cocos2dx/support/zip_support \
cocos2dx/support/user_default \
cocos2dx/support/tinyxml2 \
cocos2dx/support/image_support \
cocos2dx/support/data_support \
cocos2dx/support/component \
cocos2dx/support \
cocos2dx/sprite_nodes \
cocos2dx/shaders \
cocos2dx/script_support \
cocos2dx/platform/wp8 \
cocos2dx/platform/winrt \
cocos2dx/platform/win32 \
cocos2dx/platform/tizen \
cocos2dx/platform/third_party/winrt/angleproject/tests/preprocessor_tests \
cocos2dx/platform/third_party/winrt/angleproject/tests/compiler_tests \
cocos2dx/platform/third_party/winrt/angleproject/src/third_party/winrt/ThreadEmulation \
cocos2dx/platform/third_party/winrt/angleproject/src/third_party/murmurhash \
cocos2dx/platform/third_party/winrt/angleproject/src/third_party/compiler \
cocos2dx/platform/third_party/winrt/angleproject/src/libGLESv2 \
cocos2dx/platform/third_party/winrt/angleproject/src/libGLESv2/renderer \
cocos2dx/platform/third_party/winrt/angleproject/src/libEGL \
cocos2dx/platform/third_party/winrt/angleproject/src/glslPrecompiler \
cocos2dx/platform/third_party/winrt/angleproject/src/compiler \
cocos2dx/platform/third_party/winrt/angleproject/src/compiler/timing \
cocos2dx/platform/third_party/winrt/angleproject/src/compiler/preprocessor \
cocos2dx/platform/third_party/winrt/angleproject/src/compiler/depgraph \
cocos2dx/platform/third_party/winrt/angleproject/src/common \
cocos2dx/platform/third_party/winrt/angleproject/samples/translator \
cocos2dx/platform/third_party/winrt/angleproject/samples/gles2_book/TextureWrap \
cocos2dx/platform/third_party/winrt/angleproject/samples/gles2_book/Stencil_Test \
cocos2dx/platform/third_party/winrt/angleproject/samples/gles2_book/Simple_VertexShader \
cocos2dx/platform/third_party/winrt/angleproject/samples/gles2_book/Simple_TextureCubemap \
cocos2dx/platform/third_party/winrt/angleproject/samples/gles2_book/Simple_Texture2D \
cocos2dx/platform/third_party/winrt/angleproject/samples/gles2_book/PostSubBuffer \
cocos2dx/platform/third_party/winrt/angleproject/samples/gles2_book/ParticleSystem \
cocos2dx/platform/third_party/winrt/angleproject/samples/gles2_book/MultipleRenderTargets \
cocos2dx/platform/third_party/winrt/angleproject/samples/gles2_book/MultiTexture \
cocos2dx/platform/third_party/winrt/angleproject/samples/gles2_book/MipMap2D \
cocos2dx/platform/third_party/winrt/angleproject/samples/gles2_book/Hello_Triangle \
cocos2dx/platform/third_party/winrt/angleproject/samples/gles2_book/Common \
cocos2dx/platform/third_party/winrt/angleproject/samples/gles2_book/Common/Win32 \
cocos2dx/platform/third_party/winrt/angleproject/samples/angle/Simple_Instancing/Simple_Instancing_winrt \
cocos2dx/platform/third_party/winrt/angleproject/samples/angle/Simple_Instancing \
cocos2dx/platform/third_party/winrt/angleproject/samples/RotatingCube \
cocos2dx/platform/third_party/winrt/angleproject/samples/Asteroids/src/res \
cocos2dx/platform/third_party/winrt/angleproject/samples/Asteroids/src \
cocos2dx/platform/third_party/winrt/angleproject/samples/Asteroids/src/game \
cocos2dx/platform/third_party/winrt/angleproject/samples/Asteroids/src/engine \
cocos2dx/platform/third_party/winrt/angleproject/samples/Asteroids \
cocos2dx/platform/third_party/winrt/angleproject/samples/Asteroids/glm/core \
cocos2dx/platform/third_party/marmalade/libwebp/utils \
cocos2dx/platform/third_party/marmalade/libwebp/mux \
cocos2dx/platform/third_party/marmalade/libwebp/enc \
cocos2dx/platform/third_party/marmalade/libwebp/dsp \
cocos2dx/platform/third_party/marmalade/libwebp/dec \
cocos2dx/platform/third_party/marmalade/libtiff/source \
cocos2dx/platform/third_party/marmalade/libtiff/headers \
cocos2dx/platform/third_party/marmalade/freetype/src/winfonts \
cocos2dx/platform/third_party/marmalade/freetype/src/type42 \
cocos2dx/platform/third_party/marmalade/freetype/src/type1 \
cocos2dx/platform/third_party/marmalade/freetype/src/truetype \
cocos2dx/platform/third_party/marmalade/freetype/src/tools \
cocos2dx/platform/third_party/marmalade/freetype/src/tools/ftrandom \
cocos2dx/platform/third_party/marmalade/freetype/src/smooth \
cocos2dx/platform/third_party/marmalade/freetype/src/sfnt \
cocos2dx/platform/third_party/marmalade/freetype/src/raster \
cocos2dx/platform/third_party/marmalade/freetype/src/psnames \
cocos2dx/platform/third_party/marmalade/freetype/src/pshinter \
cocos2dx/platform/third_party/marmalade/freetype/src/psaux \
cocos2dx/platform/third_party/marmalade/freetype/src/pfr \
cocos2dx/platform/third_party/marmalade/freetype/src/pcf \
cocos2dx/platform/third_party/marmalade/freetype/src/otvalid \
cocos2dx/platform/third_party/marmalade/freetype/src/lzw \
cocos2dx/platform/third_party/marmalade/freetype/src/gzip \
cocos2dx/platform/third_party/marmalade/freetype/src/gxvalid \
cocos2dx/platform/third_party/marmalade/freetype/src/cid \
cocos2dx/platform/third_party/marmalade/freetype/src/cff \
cocos2dx/platform/third_party/marmalade/freetype/src/cache \
cocos2dx/platform/third_party/marmalade/freetype/src/bdf \
cocos2dx/platform/third_party/marmalade/freetype/src/base \
cocos2dx/platform/third_party/marmalade/freetype/src/autofit \
cocos2dx/platform \
cocos2dx/platform/nacl \
cocos2dx/platform/marmalade \
cocos2dx/platform/linux \
cocos2dx/platform/ios \
cocos2dx/platform/emscripten \
cocos2dx/platform/blackberry \
cocos2dx/platform/android/jni \
cocos2dx/platform/android \
cocos2dx/particle_nodes \
cocos2dx/misc_nodes \
cocos2dx/menu_nodes \
cocos2dx/layers_scenes_transitions_nodes \
cocos2dx/label_nodes \
cocos2dx/keypad_dispatcher \
cocos2dx/kazmath/src \
cocos2dx/kazmath/src/GL \
cocos2dx/effects \
cocos2dx/draw_nodes \
cocos2dx \
cocos2dx/cocoa \
cocos2dx/base_nodes \
cocos2dx/actions \
Classes \
Classes/JNICalls \

